export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const ORDER_ASYNC_FAIL = 'ORDER_ASYNC_FAIL';
export const START_ORDER_ASYNC = 'START_ORDER_ASYNC';
export const SET_ORDERS = 'SET_ORDERS';